### ISSUE TITLE
Failed to compile - imports should occur after import of `./Tree-utils`

### ISSUE THREAD

**Issue by learlyhpl** [GeReV/hocr-editor#1]
Hello, not sure if this is an issue or a mistake on my part. I'm trying to run the start script with yarn and I get the following 'failed to compile' errors:

./src/components/SortableTree/components/Tree/Tree.tsx
  Line 1:1:   `react` import should occur after import of `./Tree-utils`                         import/order
  Line 2:1:   `react-window` import should occur after import of `./Tree-utils`                  import/order
  Line 3:1:   `react-virtualized-auto-sizer` import should occur after import of `./Tree-utils`  import/order
  Line 4:1:   `react-beautiful-dnd` import should occur after import of `./Tree-utils`           import/order
  Line 17:1:  `css-box-model` import should occur after import of `./Tree-utils`                 import/order

Any help much appreciated. I'm on a Windows 10 machine. Very interested in using your hOCR editor. Thanks.

**Comment by venkatapathy** [comment]
Any solution for this? I am also facing the same issue. I understand that it is because of recent version of a npm package. Any workaround to ignore this?
